from .integration_interface import IntegrationInterface
from .get_list_exercise import GetListExerciseInterface
from .create_class import CreateClassInterface
from .find_user import FindUserInterface
from .register_user import RegisterUserInterface
from .find_class import FindClassInterface
from .register_list_exercise import RegisterListExerciseInterface
from .create_group import CreateGroupInterface