version: 2.1
executors:
  python-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  deploy:
    executor: python-executor
    steps:
      - checkout

      # Instale as dependências da sua aplicação
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_project.sh”
      # Faça o deploy para a máquina virtual via SSH

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: feat/api/exercise
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feat/api/exercise
