version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.8

    working_directory: ~/repo

    steps:
      - checkout

      - run: pip install --upgrade pip

      - run: pip install -r requirements_test.txt

      - run: pytest -m unit
      
  deploy:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v cedric@200.137.197.240 -p 30240 "./deploy.sh"


workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build