version: 2.1

jobs:
  build:
    environment:
      DATABASE_URL: $DATABASE_URL
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run: pip install -r requirements.txt

      - run: pytest


  deploy:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Install AWS CLI"
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
            sudo apt-get install -y python3-pip
            sudo pip3 install awsebcli --upgrade

      - run: ssh -oStrictHostKeyChecking=no -v cedric@200.137.197.240 -p 30240 “./deploy_project.sh”

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: feat/user
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feat/user



