from .integration_mrplato import IntegrationMrplato
from .get_list_exercise import GetListExercise
from .create_class import CreateClass
from .register_user import RegisterUser
from .find_class import FindClass
from .find_user import FindUser
from .register_list_exercise import RegisterListExercise
from .create_group import CreateGroup
from .register_member import RegisterMember
from .find_group import FindGroup
from .select_form_mrplato import SelectForm
from .insert_hyposthesis import InsertHypothesis